spring.application.name=auction-backend
server.port=8080
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.auction.backend.auction.model
mybatis.configuration.map-underscore-to-camel-case=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
